apiVersion: v1
kind: Service
metadata:
  name: devops-poc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-poc
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
